[[main]]
name = "Blog"
weight = 4
url = "blog/"

[[main]]
name = "Docs"
weight = 2
url = "docs/"

[[main]]
name = "Cases"
weight = 2
url = "cases/"

[[main]]
name = "EA Viden"
weight = 3
url = "https://www.eaviden.dk/project/implementering-af-cyber-resilience-act-i-smver/"
